services:
  tidb:
    image: pingcap/tidb:latest
    command: ["--store=mocktikv", "--log-file="]
    ports:
      - "14000:4000"   # MySQL protocol
    environment:
      # TiDB は root 無パスで入れる
      - TZ=UTC
